version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: abcd_gmbh
      JWT_SECRET: 3ac14017de603747356f0fc52ca2ba196bcf10d6ea0e8364026794f0ec1a748fe4592cf8ef89b4617ba2fbfb33f03c6b99c9c081aff3f152a75467b06af76111
    depends_on: []
